name: Run Python Script

on:
  push:
    branches:
      - main

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Python Script
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: python your_script.py
